### ISSUE TITLE
申请加入BP

### ISSUE THREAD

**Issue by loganwu** [eostea/EOS-Party-Testnet#1]
公钥： EOS5THGjwWqpVxgqTSQvfA4vwDYCE4AdnHMXsGYaTVG3vS5FfRM2z
名字： chinababa

**Comment by strahe** [comment]
你那边连上吗?

我门加上去了, 但是没看到你出块.

**Comment by strahe** [comment]
成功加上了, 出块正常. issue先关闭了.
