### ISSUE TITLE
Apply to join eos party testnet

### ISSUE THREAD

**Issue by Alex-toughman** [eostea/EOS-Party-Testnet#10]
Server Location: TW
Organisation: eos.store
node ip/domain: testnet.eos.store
Port (http):8888
Port (p2p):9876
producer name:eos.store
your public key:EOS7j5nLtLd5uAQdheG8rjKJEJ9xb5dvqjM2ivHBgvLwuf5X2jugZ

**Comment by strahe** [comment]
Hi, did you start the eos node? I found that your server 9876 port is closed.

**Comment by Alex-toughman** [comment]
yes, I haven't lanched nodeos. But Now it works

**Comment by strahe** [comment]
Done.

**Comment by strahe** [comment]
Is your server running for a long time? Can I add your node to config.ini?

**Comment by Alex-toughman** [comment]
yes, of course. I want to as a BP node in your testnet of eos.

**Comment by Alex-toughman** [comment]
BTW, Do I need to modify any configurations in my local setup?

**Comment by Alex-toughman** [comment]
hello, I got following infomations after I generate 12 blocks, what is it mean?
392580ms thread-0   fork_database.cpp:78          _push_block          ] Number of missed blocks: 12

392580ms thread-0   chain_controller.cpp:1406     validate_block_heade ] head_block_time 2018-04-20T08:06:26.000, next_block 2018-04-20T08:06:32.500, block_interval 500
392580ms thread-0   chain_controller.cpp:1408     validate_block_heade ] Did not produce block within block_interval 500ms, took 6500ms)

**Comment by strahe** [comment]
This is normal, this log indicates that 2 BPs in the network have missed the block time.

> BTW, Do I need to modify any configurations in my local setup?

No,

**Comment by Alex-toughman** [comment]
thank you for your reply, I have another question, if I start another nodeos and with the save configurations (private key, public key, agent name ...) , what will happen, I test this case in my private setup, it works. 
And If I stop one of them, the another will generate block continuly, is that ok?

**Comment by strahe** [comment]
If I understand correctly, your two nodes will produce blocks separately, but only one node block is valid, depending on the next block producer.

> And If I stop one of them, the another will generate block continuly, is that ok?

I think yes.

**Comment by strahe** [comment]
I read from the documentation, but I haven't tested it yet. I hope to help you.

**Comment by Alex-toughman** [comment]
hello, Can I re-join your test net?

**Comment by strahe** [comment]
@onecool2 yes, you need too update `genesis.json` file.
