### ISSUE TITLE
EOS TESTNET APPLICATION

### ISSUE THREAD

**Issue by LanfordCai** [eostea/EOS-Party-Testnet#11]
IP: 35.189.173.101
port: 默认
producer-name = venezia
public-key：EOS74RPWbVK851aDFr7rUJZEpfYpUMsqzRmjDapReBJPttQgZuNxn

**Comment by strahe** [comment]
Hi, We now only accept stable nodes as BP. You can temporarily synchronize the data as a full node. If necessary, apply for BP again.
