### ISSUE TITLE
BP申请

### ISSUE THREAD

**Issue by cryptopeng** [eostea/EOS-Party-Testnet#12]
* Server Location : Ottawa
* Organisation: eos90s
* node ip/domain: 47.100.6.5
* Port (http): 8888
* Port (p2p): 9876
* producer name: eosninezeros
* your public key: EOS5mG4G39buCjcSXUKmLYgfe1rkJk3HYWmrWf8bK7DkhTYf5Pkne

**Comment by strahe** [comment]
已添加.
