### ISSUE TITLE
Apply eos party testnet

### ISSUE THREAD

**Issue by LiaoPeng** [eostea/EOS-Party-Testnet#2]
Hello, can I access the testnet.

**Comment by strahe** [comment]
yes

**Comment by LiaoPeng** [comment]
Can I have you QQ account or Wechat account?

**Comment by strahe** [comment]
wechat: eosiochina

这是中文社区的小秘书, 个人微信不方便在这里公布, 加了后会拉你进我们中文社区技术群.

你也可以在我们中文社区提问: https://eosfans.io/

**Comment by LiaoPeng** [comment]
Fine, I had register the eosfans account before.
