### ISSUE TITLE
申请加入测试网络

### ISSUE THREAD

**Issue by echocamel** [eostea/EOS-Party-Testnet#7]
节点信息
- Server Location
阿里云香港B
- Organisation
个人
- node ip/domain
47.52.11.223
- Port (http)
8888
- Port (p2p)
9876
- producer name 
youyoueos
- your public key
EOS89vDtjknhuu7ARHCxBoR4C4aQ3TgdPuuPEZYZEF6E8ppcauyCN

**Comment by strahe** [comment]
已添加

**Comment by strahe** [comment]
Hi, 我们网络里没有看到你出块了, 你退出了还是?

如果没有退出需要你重启下节点, 谢谢.
