### ISSUE TITLE
eos party testnet 申请

### ISSUE THREAD

**Issue by macX-1** [eostea/EOS-Party-Testnet#9]
ip: 45.77.29.239
port: 默认
producer-name = westos
public-key：EOS66gDovgxEgqwQDv8G38SDphKcF65i7UtvoFsbspPbm4yazM3rr

**Comment by strahe** [comment]
我们已经加了, 但是一直没看到你出块.
你在检查下本地节点?

**Comment by macX-1** [comment]
我按照教程使用docker部署，容器正常运行啊，这个该如何排查？

**Comment by Lomect** [comment]
检查一下config.ini文件里面：
```
p2p-peer-address 
plugin = eosio::producer_plugin
```

**Comment by macX-1** [comment]
默认配置我没有改过，需要调整嘛？
#The public endpoint of a peer node to connect to. Use multiple p2p-peer-address options as needed to compose a network.
p2p-peer-address = cn.party.eosfans.io:9876
p2p-peer-address = hk.party.eosfans.io:9876
p2p-peer-address = 116.196.72.43:9876
#Plugin(s) to enable, may be specified multiple times
#plugin =
#Plugin(s) to enable, may be specified multiple times
plugin = eosio::producer_plugin
plugin = eosio::chain_api_plugin
plugin = eosio::wallet_api_plugin
plugin = eosio::account_history_api_plugin
plugin = eosio::http_plugin
#plugin = eosio::mongo_db_plugin

**Comment by strahe** [comment]
贴下你的日志?

**Comment by macX-1** [comment]
我贴一下异常的部分
*************************************
*                                   *
*  --   Wallet NOT on localhost  -- *
*  - Password and/or Private Keys - *
*  - are transferred unencrypted. - *
*                                   *
*************************************

push block #94 from eosio 2018-04-18T02:44:01.500  0000005e1ba71eba60b264aea7c20a7f5d93abe7b52483cc37cfd94e318bcd6c lib: 93 success
push block #95 from eosio 2018-04-18T02:44:02.000  0000005fd733c1bf8111ee26fb1ab6d837e1f7be29290bba2a093de4b21c96a8 lib: 94 success
push block #96 from eosio 2018-04-18T02:44:02.500  00000060e3525ecb414c4f845846f49d2475b6f59e3da8bafb2f5b7b4869d857 lib: 95 success
push block #97 from eosio 2018-04-18T02:44:03.000  000000616094400ed50f58ec353740e12b94c2ec37c61bfdab18bbf76088b73e lib: 96 success
push block #98 from eosio 2018-04-18T02:44:03.500  00000062881c3e93f7902354809316dd2ea3bcc71ffefb3c77798b70e5b81182 lib: 97 success
push block #99 from eosio 2018-04-18T02:44:04.000  00000063ce026d7ee2f63e36b8963826d2e60f815d5a88eb424a2a31d2ecdd2f lib: 98 success
push block #100 from eosio 2018-04-18T02:44:04.500  000000648b613528fcffbbdc582d37506e17da9528b018474f1eb982db8522e9 lib: 99 success
**# 106962ms thread-0   net_plugin.cpp:1196           request_next_chunk   ] unable to find previous source connection in connections list**
push block #101 from eosio 2018-04-18T02:44:05.000  000000655d1323a80ccb7f126f4b5102d2bfe14b9b0b0d43ab48f3b6bfd6cd32 lib: 100 success
push block #102 from eosio 2018-04-18T02:44:05.500  000000662809664e5361418a20c7aca1b93d72a5fbd043773f487969525fdd7d lib: 101 success
push block #103 from eosio 2018-04-18T02:44:06.000  000000675979fdea26d6e46eca9a57c10ea7755c33f776645f841fcb78832f00 lib: 102 success
push block #104 from eosio 2018-04-18T02:44:06.500  00000068109b0b2a742ba441ac4808d163a8e320826721d07445f8afcac90731 lib: 103 success
push block #105 from eosio 2018-04-18T02:44:07.000  00000069dd40b3e1de5c6faf0479311589c727796c1f4d7f0b879c451f4ae9da lib: 104 success
push block #106 from eosio 2018-04-18T02:44:07.500  0000006a43433ea419d3827e6eb5a738eb68bd7302af68098b65d16fdafd8b87 lib: 105 success

**Comment by strahe** [comment]
网络已经重启了,  建议你更新下 `genesis.json` 文件后重启节点, 

由于之前的很多BP下线了, 导致网络失控, 所以暂时我们只接受稳定的BP, 其他的可以作为全节点同步数据, 功能相同.
